### ISSUE TITLE
AttributeError: module 'higra' has no attribute 'weight_graph_function'

### ISSUE THREAD

**Issue by liuxy1103** [garridoq/malis-project#1]

**Comment by liuxy1103** [comment]
I install the library by "pip install higra"

**Comment by garridoq** [comment]
A breaking change was introduced in Higra 0.5 (https://higra.readthedocs.io/en/stable/changelog.html#id48) which I assume is the cause of the error.
Installing an older version of Higra (like 0.4.5) should fix this. I am not sure exactly which version we used at the time since it has been a while since we worked on this project.
You can do this with the following command : `pip install higra==0.4.5`

If it still doesn't work, try downgrading the version again or let me know what is the new issue.
If you need a newer version (not necessary to run this code), the description of the change in version 0.5.0 should give you enough pointers to reformat the necessary part of the code.

**Comment by liuxy1103** [comment]
Thanks for your reply. I use the python3.8 and the version supported is required to be higher than 0.5.0. I will try a lower version.
